use most recent API response during create to populate state
fixes issues surfaced in the most recent TF framework test runner, eg:

```
=== NAME  TestAccDatabaseResource
    database_resource_test.go:15: Step 2/3 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        - 	"ready":                  "false",
        + 	"ready":                  "true",
        - 	"schema_last_updated_at": "2024-11-21T05:12:18.211Z",
        + 	"schema_last_updated_at": "2024-11-21T05:12:44.423Z",
        - 	"state":                  "pending",
        + 	"state":                  "ready",
        - 	"updated_at":             "2024-11-21T05:12:18.421Z",
        + 	"updated_at":             "2024-11-21T05:12:44.592Z",
          }
--- FAIL: TestAccDatabaseResource (34.17s)
=== CONT  TestAccPasswordResource
=== NAME  TestAccBranchResource
    branch_resource_test.go:16: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        - 	"ready":                  "false",
        + 	"ready":                  "true",
        - 	"schema_last_updated_at": "2024-11-21T05:12:51.044Z",
        + 	"schema_last_updated_at": "2024-11-21T05:12:51.225Z",
        - 	"updated_at":             "2024-11-21T05:12:51.044Z",
        + 	"updated_at":             "2024-11-21T05:13:09.193Z",
          }
--- FAIL: TestAccBranchResource (56.72s)
```